### PR TITLE
Compatibility to Mantis 2.21.x

### PR DESCRIPTION
**Pull request by gruessung**
CSS class rename from status-X-color to status-X-bg

### CODE REVIEW

**Comment by gruessung** [comment]
status_config.php create following CSS:

```
.status-90-fg { color: #848484; }
.status-90-bg { background-color: #848484; }
```

**Comment by wiz78** [comment]
thanks. This patch is already in the master tree, though: https://github.com/wiz78/BetterStatusColors/commit/5590e2333b12b7fad6e06b83d4c6008d916b3d66

The latest commit in master changed it from -fg to -color because mantis changed again after version 2.21

**Comment by gruessung** [comment]
I'm sorry :)
Github show an old version of "BetterStatusColors.js" on master:
github-test

**Comment by wiz78** [comment]
uh, right. I guess I was looking elsewhere :-)

**Pull request merged**
